name: Polling App CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Compose Build
      run: docker-compose -f docker-compose.yml build

    - name: Compose Up
      run: docker-compose -f docker-compose.yml up -d
